language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - python setup.py --quiet build --build-base=".build-$TRAVIS_PYTHON_VERSION" install

script:
    - python setup.py test
